apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chart.fullname" . }}
  labels:
    {{- include "todo-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    {{- include "todo-chart.selectorLabels" . | nindent 4 }}

